version: '3.7'

services:
  client:
    env_file:
      - .env
    image: ${PROJECT_NAME}-client-${NODE_ENV}
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - ${WEB_PORT}:3000
    stdin_open: true
    networks:
      - client-network
    restart: unless-stopped

networks:
  client-network:
    driver: bridge
